server:
  port: 8998
  shutdown: graceful
user:
  admin:
    id: admin
    password: admin

spring:
  data:
    mongodb:
      port: 27017
      database: mini-mart
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/service
          jwk-set-uri: http://localhost:8080/realms/service/protocol/openid-connect/certs
